AllCops:
  TargetRubyVersion: 2.3

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: False

Metrics/MethodLength:
  Enabled: False

Style/WordArray:
  Exclude:
    - 'spec/markov_noodles_spec.rb'

